package com.currencyfair.service.base;

import com.currencyfair.model.Trade;

import com.currencyfair.service.TradeService;
import com.currencyfair.service.persistence.TradePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the trade remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.currencyfair.service.impl.TradeServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.currencyfair.service.impl.TradeServiceImpl
 * @see com.currencyfair.service.TradeServiceUtil
 * @generated
 */
public abstract class TradeServiceBaseImpl extends BaseServiceImpl
    implements TradeService, IdentifiableBean {
    @BeanReference(type = com.currencyfair.service.TradeLocalService.class)
    protected com.currencyfair.service.TradeLocalService tradeLocalService;
    @BeanReference(type = com.currencyfair.service.TradeService.class)
    protected com.currencyfair.service.TradeService tradeService;
    @BeanReference(type = TradePersistence.class)
    protected TradePersistence tradePersistence;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    private String _beanIdentifier;
    private ClassLoader _classLoader;
    private TradeServiceClpInvoker _clpInvoker = new TradeServiceClpInvoker();

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.currencyfair.service.TradeServiceUtil} to access the trade remote service.
     */

    /**
     * Returns the trade local service.
     *
     * @return the trade local service
     */
    public com.currencyfair.service.TradeLocalService getTradeLocalService() {
        return tradeLocalService;
    }

    /**
     * Sets the trade local service.
     *
     * @param tradeLocalService the trade local service
     */
    public void setTradeLocalService(
        com.currencyfair.service.TradeLocalService tradeLocalService) {
        this.tradeLocalService = tradeLocalService;
    }

    /**
     * Returns the trade remote service.
     *
     * @return the trade remote service
     */
    public com.currencyfair.service.TradeService getTradeService() {
        return tradeService;
    }

    /**
     * Sets the trade remote service.
     *
     * @param tradeService the trade remote service
     */
    public void setTradeService(
        com.currencyfair.service.TradeService tradeService) {
        this.tradeService = tradeService;
    }

    /**
     * Returns the trade persistence.
     *
     * @return the trade persistence
     */
    public TradePersistence getTradePersistence() {
        return tradePersistence;
    }

    /**
     * Sets the trade persistence.
     *
     * @param tradePersistence the trade persistence
     */
    public void setTradePersistence(TradePersistence tradePersistence) {
        this.tradePersistence = tradePersistence;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    public void afterPropertiesSet() {
        Class<?> clazz = getClass();

        _classLoader = clazz.getClassLoader();
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    @Override
    public Object invokeMethod(String name, String[] parameterTypes,
        Object[] arguments) throws Throwable {
        Thread currentThread = Thread.currentThread();

        ClassLoader contextClassLoader = currentThread.getContextClassLoader();

        if (contextClassLoader != _classLoader) {
            currentThread.setContextClassLoader(_classLoader);
        }

        try {
            return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
        } finally {
            if (contextClassLoader != _classLoader) {
                currentThread.setContextClassLoader(contextClassLoader);
            }
        }
    }

    protected Class<?> getModelClass() {
        return Trade.class;
    }

    protected String getModelClassName() {
        return Trade.class.getName();
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = tradePersistence.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
