package com.currencyfair.model.impl;

import com.currencyfair.model.Trade;
import com.currencyfair.model.TradeModel;
import com.currencyfair.model.TradeSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Trade service. Represents a row in the &quot;TradeService_Trade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.currencyfair.model.TradeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TradeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TradeImpl
 * @see com.currencyfair.model.Trade
 * @see com.currencyfair.model.TradeModel
 * @generated
 */
@JSON(strict = true)
public class TradeModelImpl extends BaseModelImpl<Trade> implements TradeModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a trade model instance should use the {@link com.currencyfair.model.Trade} interface instead.
     */
    public static final String TABLE_NAME = "TradeService_Trade";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "tradeId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "currencyFrom", Types.VARCHAR },
            { "currencyTo", Types.VARCHAR },
            { "amountSell", Types.DOUBLE },
            { "amountBuy", Types.DOUBLE },
            { "rate", Types.DOUBLE },
            { "timePlaced", Types.TIMESTAMP },
            { "originatingCountry", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table TradeService_Trade (uuid_ VARCHAR(75) null,tradeId LONG not null primary key,userId LONG,currencyFrom VARCHAR(75) null,currencyTo VARCHAR(75) null,amountSell DOUBLE,amountBuy DOUBLE,rate DOUBLE,timePlaced DATE null,originatingCountry VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table TradeService_Trade";
    public static final String ORDER_BY_JPQL = " ORDER BY trade.tradeId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY TradeService_Trade.tradeId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.currencyfair.model.Trade"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.currencyfair.model.Trade"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.com.currencyfair.model.Trade"),
            true);
    public static long USERID_COLUMN_BITMASK = 1L;
    public static long UUID_COLUMN_BITMASK = 2L;
    public static long TRADEID_COLUMN_BITMASK = 4L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.currencyfair.model.Trade"));
    private static ClassLoader _classLoader = Trade.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] { Trade.class };
    private String _uuid;
    private String _originalUuid;
    private long _tradeId;
    private long _userId;
    private String _userUuid;
    private long _originalUserId;
    private boolean _setOriginalUserId;
    private String _currencyFrom;
    private String _currencyTo;
    private double _amountSell;
    private double _amountBuy;
    private double _rate;
    private Date _timePlaced;
    private String _originatingCountry;
    private long _columnBitmask;
    private Trade _escapedModel;

    public TradeModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static Trade toModel(TradeSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        Trade model = new TradeImpl();

        model.setUuid(soapModel.getUuid());
        model.setTradeId(soapModel.getTradeId());
        model.setUserId(soapModel.getUserId());
        model.setCurrencyFrom(soapModel.getCurrencyFrom());
        model.setCurrencyTo(soapModel.getCurrencyTo());
        model.setAmountSell(soapModel.getAmountSell());
        model.setAmountBuy(soapModel.getAmountBuy());
        model.setRate(soapModel.getRate());
        model.setTimePlaced(soapModel.getTimePlaced());
        model.setOriginatingCountry(soapModel.getOriginatingCountry());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<Trade> toModels(TradeSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<Trade> models = new ArrayList<Trade>(soapModels.length);

        for (TradeSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _tradeId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setTradeId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _tradeId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return Trade.class;
    }

    @Override
    public String getModelClassName() {
        return Trade.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("tradeId", getTradeId());
        attributes.put("userId", getUserId());
        attributes.put("currencyFrom", getCurrencyFrom());
        attributes.put("currencyTo", getCurrencyTo());
        attributes.put("amountSell", getAmountSell());
        attributes.put("amountBuy", getAmountBuy());
        attributes.put("rate", getRate());
        attributes.put("timePlaced", getTimePlaced());
        attributes.put("originatingCountry", getOriginatingCountry());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long tradeId = (Long) attributes.get("tradeId");

        if (tradeId != null) {
            setTradeId(tradeId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String currencyFrom = (String) attributes.get("currencyFrom");

        if (currencyFrom != null) {
            setCurrencyFrom(currencyFrom);
        }

        String currencyTo = (String) attributes.get("currencyTo");

        if (currencyTo != null) {
            setCurrencyTo(currencyTo);
        }

        Double amountSell = (Double) attributes.get("amountSell");

        if (amountSell != null) {
            setAmountSell(amountSell);
        }

        Double amountBuy = (Double) attributes.get("amountBuy");

        if (amountBuy != null) {
            setAmountBuy(amountBuy);
        }

        Double rate = (Double) attributes.get("rate");

        if (rate != null) {
            setRate(rate);
        }

        Date timePlaced = (Date) attributes.get("timePlaced");

        if (timePlaced != null) {
            setTimePlaced(timePlaced);
        }

        String originatingCountry = (String) attributes.get(
                "originatingCountry");

        if (originatingCountry != null) {
            setOriginatingCountry(originatingCountry);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getTradeId() {
        return _tradeId;
    }

    @Override
    public void setTradeId(long tradeId) {
        _columnBitmask = -1L;

        _tradeId = tradeId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _columnBitmask |= USERID_COLUMN_BITMASK;

        if (!_setOriginalUserId) {
            _setOriginalUserId = true;

            _originalUserId = _userId;
        }

        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    public long getOriginalUserId() {
        return _originalUserId;
    }

    @JSON
    @Override
    public String getCurrencyFrom() {
        if (_currencyFrom == null) {
            return StringPool.BLANK;
        } else {
            return _currencyFrom;
        }
    }

    @Override
    public void setCurrencyFrom(String currencyFrom) {
        _currencyFrom = currencyFrom;
    }

    @JSON
    @Override
    public String getCurrencyTo() {
        if (_currencyTo == null) {
            return StringPool.BLANK;
        } else {
            return _currencyTo;
        }
    }

    @Override
    public void setCurrencyTo(String currencyTo) {
        _currencyTo = currencyTo;
    }

    @JSON
    @Override
    public double getAmountSell() {
        return _amountSell;
    }

    @Override
    public void setAmountSell(double amountSell) {
        _amountSell = amountSell;
    }

    @JSON
    @Override
    public double getAmountBuy() {
        return _amountBuy;
    }

    @Override
    public void setAmountBuy(double amountBuy) {
        _amountBuy = amountBuy;
    }

    @JSON
    @Override
    public double getRate() {
        return _rate;
    }

    @Override
    public void setRate(double rate) {
        _rate = rate;
    }

    @JSON(include = false)
    @Override
    public Date getTimePlaced() {
        return _timePlaced;
    }

    @Override
    public void setTimePlaced(Date timePlaced) {
        _timePlaced = timePlaced;
    }

    @JSON
    @Override
    public String getOriginatingCountry() {
        if (_originatingCountry == null) {
            return StringPool.BLANK;
        } else {
            return _originatingCountry;
        }
    }

    @Override
    public void setOriginatingCountry(String originatingCountry) {
        _originatingCountry = originatingCountry;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            Trade.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public Trade toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (Trade) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        TradeImpl tradeImpl = new TradeImpl();

        tradeImpl.setUuid(getUuid());
        tradeImpl.setTradeId(getTradeId());
        tradeImpl.setUserId(getUserId());
        tradeImpl.setCurrencyFrom(getCurrencyFrom());
        tradeImpl.setCurrencyTo(getCurrencyTo());
        tradeImpl.setAmountSell(getAmountSell());
        tradeImpl.setAmountBuy(getAmountBuy());
        tradeImpl.setRate(getRate());
        tradeImpl.setTimePlaced(getTimePlaced());
        tradeImpl.setOriginatingCountry(getOriginatingCountry());

        tradeImpl.resetOriginalValues();

        return tradeImpl;
    }

    @Override
    public int compareTo(Trade trade) {
        int value = 0;

        if (getTradeId() < trade.getTradeId()) {
            value = -1;
        } else if (getTradeId() > trade.getTradeId()) {
            value = 1;
        } else {
            value = 0;
        }

        if (value != 0) {
            return value;
        }

        return 0;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Trade)) {
            return false;
        }

        Trade trade = (Trade) obj;

        long primaryKey = trade.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        TradeModelImpl tradeModelImpl = this;

        tradeModelImpl._originalUuid = tradeModelImpl._uuid;

        tradeModelImpl._originalUserId = tradeModelImpl._userId;

        tradeModelImpl._setOriginalUserId = false;

        tradeModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<Trade> toCacheModel() {
        TradeCacheModel tradeCacheModel = new TradeCacheModel();

        tradeCacheModel.uuid = getUuid();

        String uuid = tradeCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            tradeCacheModel.uuid = null;
        }

        tradeCacheModel.tradeId = getTradeId();

        tradeCacheModel.userId = getUserId();

        tradeCacheModel.currencyFrom = getCurrencyFrom();

        String currencyFrom = tradeCacheModel.currencyFrom;

        if ((currencyFrom != null) && (currencyFrom.length() == 0)) {
            tradeCacheModel.currencyFrom = null;
        }

        tradeCacheModel.currencyTo = getCurrencyTo();

        String currencyTo = tradeCacheModel.currencyTo;

        if ((currencyTo != null) && (currencyTo.length() == 0)) {
            tradeCacheModel.currencyTo = null;
        }

        tradeCacheModel.amountSell = getAmountSell();

        tradeCacheModel.amountBuy = getAmountBuy();

        tradeCacheModel.rate = getRate();

        Date timePlaced = getTimePlaced();

        if (timePlaced != null) {
            tradeCacheModel.timePlaced = timePlaced.getTime();
        } else {
            tradeCacheModel.timePlaced = Long.MIN_VALUE;
        }

        tradeCacheModel.originatingCountry = getOriginatingCountry();

        String originatingCountry = tradeCacheModel.originatingCountry;

        if ((originatingCountry != null) && (originatingCountry.length() == 0)) {
            tradeCacheModel.originatingCountry = null;
        }

        return tradeCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(21);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", tradeId=");
        sb.append(getTradeId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", currencyFrom=");
        sb.append(getCurrencyFrom());
        sb.append(", currencyTo=");
        sb.append(getCurrencyTo());
        sb.append(", amountSell=");
        sb.append(getAmountSell());
        sb.append(", amountBuy=");
        sb.append(getAmountBuy());
        sb.append(", rate=");
        sb.append(getRate());
        sb.append(", timePlaced=");
        sb.append(getTimePlaced());
        sb.append(", originatingCountry=");
        sb.append(getOriginatingCountry());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(34);

        sb.append("<model><model-name>");
        sb.append("com.currencyfair.model.Trade");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>tradeId</column-name><column-value><![CDATA[");
        sb.append(getTradeId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>currencyFrom</column-name><column-value><![CDATA[");
        sb.append(getCurrencyFrom());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>currencyTo</column-name><column-value><![CDATA[");
        sb.append(getCurrencyTo());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>amountSell</column-name><column-value><![CDATA[");
        sb.append(getAmountSell());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>amountBuy</column-name><column-value><![CDATA[");
        sb.append(getAmountBuy());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>rate</column-name><column-value><![CDATA[");
        sb.append(getRate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>timePlaced</column-name><column-value><![CDATA[");
        sb.append(getTimePlaced());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>originatingCountry</column-name><column-value><![CDATA[");
        sb.append(getOriginatingCountry());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
