package com.currencyfair.model.impl;

import com.currencyfair.model.Trade;

import com.currencyfair.service.TradeLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Trade service. Represents a row in the &quot;TradeService_Trade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TradeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TradeImpl
 * @see com.currencyfair.model.Trade
 * @generated
 */
public abstract class TradeBaseImpl extends TradeModelImpl implements Trade {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a trade model instance should use the {@link Trade} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TradeLocalServiceUtil.addTrade(this);
        } else {
            TradeLocalServiceUtil.updateTrade(this);
        }
    }
}
