package com.currencyfair.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Trade service. Represents a row in the &quot;TradeService_Trade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.currencyfair.model.impl.TradeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.currencyfair.model.impl.TradeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Trade
 * @see com.currencyfair.model.impl.TradeImpl
 * @see com.currencyfair.model.impl.TradeModelImpl
 * @generated
 */
public interface TradeModel extends BaseModel<Trade> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a trade model instance should use the {@link Trade} interface instead.
     */

    /**
     * Returns the primary key of this trade.
     *
     * @return the primary key of this trade
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this trade.
     *
     * @param primaryKey the primary key of this trade
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this trade.
     *
     * @return the uuid of this trade
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this trade.
     *
     * @param uuid the uuid of this trade
     */
    public void setUuid(String uuid);

    /**
     * Returns the trade ID of this trade.
     *
     * @return the trade ID of this trade
     */
    public long getTradeId();

    /**
     * Sets the trade ID of this trade.
     *
     * @param tradeId the trade ID of this trade
     */
    public void setTradeId(long tradeId);

    /**
     * Returns the user ID of this trade.
     *
     * @return the user ID of this trade
     */
    public long getUserId();

    /**
     * Sets the user ID of this trade.
     *
     * @param userId the user ID of this trade
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this trade.
     *
     * @return the user uuid of this trade
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this trade.
     *
     * @param userUuid the user uuid of this trade
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the currency from of this trade.
     *
     * @return the currency from of this trade
     */
    @AutoEscape
    public String getCurrencyFrom();

    /**
     * Sets the currency from of this trade.
     *
     * @param currencyFrom the currency from of this trade
     */
    public void setCurrencyFrom(String currencyFrom);

    /**
     * Returns the currency to of this trade.
     *
     * @return the currency to of this trade
     */
    @AutoEscape
    public String getCurrencyTo();

    /**
     * Sets the currency to of this trade.
     *
     * @param currencyTo the currency to of this trade
     */
    public void setCurrencyTo(String currencyTo);

    /**
     * Returns the amount sell of this trade.
     *
     * @return the amount sell of this trade
     */
    public double getAmountSell();

    /**
     * Sets the amount sell of this trade.
     *
     * @param amountSell the amount sell of this trade
     */
    public void setAmountSell(double amountSell);

    /**
     * Returns the amount buy of this trade.
     *
     * @return the amount buy of this trade
     */
    public double getAmountBuy();

    /**
     * Sets the amount buy of this trade.
     *
     * @param amountBuy the amount buy of this trade
     */
    public void setAmountBuy(double amountBuy);

    /**
     * Returns the rate of this trade.
     *
     * @return the rate of this trade
     */
    public double getRate();

    /**
     * Sets the rate of this trade.
     *
     * @param rate the rate of this trade
     */
    public void setRate(double rate);

    /**
     * Returns the time placed of this trade.
     *
     * @return the time placed of this trade
     */
    public Date getTimePlaced();

    /**
     * Sets the time placed of this trade.
     *
     * @param timePlaced the time placed of this trade
     */
    public void setTimePlaced(Date timePlaced);

    /**
     * Returns the originating country of this trade.
     *
     * @return the originating country of this trade
     */
    @AutoEscape
    public String getOriginatingCountry();

    /**
     * Sets the originating country of this trade.
     *
     * @param originatingCountry the originating country of this trade
     */
    public void setOriginatingCountry(String originatingCountry);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Trade trade);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Trade> toCacheModel();

    @Override
    public Trade toEscapedModel();

    @Override
    public Trade toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
